---
# tasks file for neobundle-vim
- name: ghq root
  shell: "{{ansible_env.HOME}}/.go/bin/ghq root"
  register: ghq_root
  changed_when: false
- name: Clone neobundle
  ghq:
    name: Shougo/neobundle.vim
    executable: "{{neobundle_vim_ghq_executable}}"
- name: mkdir ~/.vim/bundle
  file:
    path: "{{ansible_env.HOME}}/.vim/bundle"
    state: directory
- name: Check ~/.vim/bundle/neobundle.vim
  stat:
    path: "{{ansible_env.HOME}}/.vim/bundle/neobundle.vim"
  register: st
- name: Back up ~/.vim/bundle/neobundle.vim
  shell: "mv {{ansible_env.HOME}}/.vim/bundle/neobundle.vim {{ansible_env.HOME}}/.vim/bundle/neobundle.vim.{{ansible_date_time.date}}-{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}"
  when: st.stat.exists and not st.stat.islnk
- name: Make symbolic links
  file:
    src: "{{ghq_root.stdout}}/github.com/Shougo/neobundle.vim"
    dest: "{{ansible_env.HOME}}/.vim/bundle/neobundle.vim"
    state: link
