---
# tasks file for neobundle-vim
- name: ghq root
  shell: /home/vagrant/.go/bin/ghq root
  register: ghq_root
  changed_when: false
- name: Clone neobundle
  ghq:
    name: Shougo/neobundle.vim
    executable: "{{neobundle_vim_ghq_executable}}"
- name: mkdir ~/.vim/bundle
  file:
    path: "{{ansible_env.HOME}}/.vim/bundle"
    state: directory
- name: Make symbolic links
  file:
    src: "{{ghq_root.stdout}}/github.com/Shougo/neobundle.vim"
    dest: "{{ansible_env.HOME}}/.vim/bundle/neobundle.vim"
    state: link
